### ISSUE TITLE
lr_scheduler error while training 

### ISSUE THREAD

**Issue by aviaisr** [Tramac/Lightweight-Segmentation#14]
Hi,
I am using PyTorch version '1.4.0.dev20191118' and I am trying to train mobilenet v3 large.
I am getting this error related to the lr_scheduler:

Traceback (most recent call last):
  File "C:/CP/DL_REPOSITORIES/Lightweight-Segmentation/scripts/train.py", line 291, in <module>
    trainer = Trainer(args)
  File "C:/CP/DL_REPOSITORIES/Lightweight-Segmentation/scripts/train.py", line 157, in __init__
    warmup_method=args.warmup_method)
  File "C:\CP\DL_REPOSITORIES\Lightweight-Segmentation\light\utils\lr_scheduler.py", line 154, in __init__
    super(WarmupPolyLR, self).__init__(optimizer, last_epoch)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\optim\lr_scheduler.py", line 77, in __init__
    self.step()
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\optim\lr_scheduler.py", line 150, in step
    for param_group, lr in zip(self.optimizer.param_groups, values):
UnboundLocalError: local variable 'values' referenced before assignment

Should I downgrade my PyTorch version if I want the training to work or will you support latter PyTorch versions?

Thanks.

**Comment by Tramac** [comment]
You can try pytorch 1.1.

**Comment by aviaisr** [comment]
Hi,
I tried to run this with PyTorch 1.1 but I'm still getting an error from the same code location (but a slightly different one):
Traceback (most recent call last):
  File "C:/CP/DL_REPOSITORIES/Lightweight-Segmentation/scripts/train.py", line 291, in <module>
    trainer = Trainer(args)
  File "C:/CP/DL_REPOSITORIES/Lightweight-Segmentation/scripts/train.py", line 157, in __init__
    warmup_method=args.warmup_method)
  File "C:\CP\DL_REPOSITORIES\Lightweight-Segmentation\light\utils\lr_scheduler.py", line 154, in __init__
    super(WarmupPolyLR, self).__init__(optimizer, last_epoch)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\optim\lr_scheduler.py", line 26, in __init__
    self.step(last_epoch)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\optim\lr_scheduler.py", line 52, in step
    for param_group, lr in zip(self.optimizer.param_groups, self.get_lr()):
  File "C:\CP\DL_REPOSITORIES\Lightweight-Segmentation\light\utils\lr_scheduler.py", line 168, in get_lr
    factor = pow(1 - T / N, self.power)
ZeroDivisionError: division by zero
